[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install -g serve@latest"]

[phases.build]
cmds = ["echo 'Static site - no build step required'"]

[start]
cmd = "serve -s dist/public -l $PORT"

